### ISSUE TITLE
用户自定义安装路径

### ISSUE THREAD

**Issue by Ye-Jinhong** [Thysrael/Ficus#243]
ENV：Windows11

使用安装包安装时无法指定安装目录

**Comment by Dofingert** [comment]
感谢您的反馈！

由于软件更新需要软件所在目录的写权限，相关提权措施还没有完成，目前软件是通过限制windows下的安装位置，避免用户将软件安装在特权文件夹中，保证软件可以更新的。见[相关issue](https://github.com/Thysrael/Ficus/issues/222)
