### ISSUE TITLE
图片链接的输入框过于狭窄

### ISSUE THREAD

**Issue by Ye-Jinhong** [Thysrael/Ficus#244]
ENV：Windows11

1. 图片链接的输入框过于狭窄，无法显示完全；
2. 删除按钮放置于左部靠近路径，容易误触。

![image](https://user-images.githubusercontent.com/48616668/235079154-c2e18602-63dd-459a-af04-ad14c9df5c74.png)

**Comment by Thysrael** [comment]
这是因为渲染部分采用的是 vidtor 插件，我们考虑在 beta 修改部分 UI

**Comment by Thysrael** [comment]
已经美化过啦！
