### ISSUE TITLE
安装报错：您无法打开应用程序“ficus.app”，因为这台Mac不支持此应用程序。

### ISSUE THREAD

**Issue by jayfeather9** [Thysrael/Ficus#249]
如题，intel CPU的mbp，macOS Monterey 12.0.1，最新release的arm64的dmg安装后显示这句话。（即使执行了要求的命令也不行）
是不是只支持m1的CPU？

**Comment by Dofingert** [comment]
是的，目前暂时仅支持 apple silicon，x86的mac可能需要自行从源码构建
