### ISSUE TITLE
LaTeX解析错误

### ISSUE THREAD

**Issue by ZouYuyang** [Thysrael/Ficus#251]
```
1. **将函数$f\left(x\right)=x，x∈[0,π]$展开为余弦级数. **
   $f(x)$为奇函数,将其延拓为周期为$2\pi$的偶函数$F(x)$
```

（其中的1.是有序列表，\*\*没有正常渲染

**Comment by Dofingert** [comment]
我们支持的markdown加粗语法 ** 包围起来的部分中不可以有空格，您可以尝试改为

1. **将函数$f\left(x\right)=x，x∈[0,π]$展开为余弦级数.**
   $f(x)$为奇函数,将其延拓为周期为$2\pi$的偶函数$F(x)$

**Comment by Hyggge** [comment]
目前我们暂时只支持commonMark规范，在该规范中`** **`和内部的文本之间不可以有空格。我们后续可能会考虑增强markdown语法，感谢您的指出~
![image](https://user-images.githubusercontent.com/92776215/236655024-ee660422-28ad-4cc6-bba6-cb984b3b78db.png)
