### ISSUE TITLE
“ficus”已损坏，无法打开。

### ISSUE THREAD

**Issue by Toby-Shi-cloud** [Thysrael/Ficus#256]
## 标题
“ficus”已损坏，无法打开

### 详细说明
![image](https://user-images.githubusercontent.com/85665268/235341885-1418689e-f07f-4c77-b367-341428ab2361.png)
这看起来不太合理。

### 标签
- `bug`

**Comment by Dofingert** [comment]
请您参考下载页面上的说明
'''
mac 用户请在安装后执行
sudo xattr -r -d com.apple.quarantine /Applications/ficus.app
''''
由于我们的软件没有得到苹果的签名证书，目前发布的版本并没有被签名

**Comment by Thysrael** [comment]
谢谢同学，你的问题已经在群中解决了。另外给 issue 打标签，可以在这里打标签。
![image](https://user-images.githubusercontent.com/72613958/236654744-dd7ee6ac-6946-43a9-a919-a0ebc5bdab50.png)
