### ISSUE TITLE
使用WSL2 Ubuntu启动 AppImage字体丢失

### ISSUE THREAD

**Issue by cactusBalll** [Thysrael/Ficus#258]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/91444954/235446839-c210f2f0-821e-4aed-9b15-52927494436c.png">
如上图。

**Comment by Dofingert** [comment]
wsl下默认是没有安装中文字体的，您可能可以通过在wsl下导入所有windows下的字体，或者安装中文字体解决这个问题。
