### ISSUE TITLE
在源码模式下，流程图渲染没有箭头

### ISSUE THREAD

**Issue by xiaxiaoyun926** [Thysrael/Ficus#306]
如图，在源码模式下，流程图渲染没有箭头。在文本模式下，流程图是有箭头的

**Comment by Thysrael** [comment]
感谢您的反馈，请问您能具体展示一下出现问题的代码和现象吗？

**Comment by xiaxiaoyun926** [comment]
我还能提一个小小的需求吗
希望按钮上可以添加tooltips，现在有些按钮不知道啥意思，意义不明确

**Comment by Thysrael** [comment]
> 我还能提一个小小的需求吗 希望按钮上可以添加tooltips，现在有些按钮不知道啥意思，意义不明确

感谢反馈，目前 dev 分支上已经增加了这个功能，可以拉取 dev 分支后使用 `yarn build` 自行构建，也可以稍等我们一到两周发布新的版本，这个功能我们在第一版发布的时候忘记了。

具体的功能说明也可以在[官网功能介绍](https://ficus.world/pages/b4868b/)中找到。
